Traceback (most recent call last):
  File "/mnt/beegfs-ssd/home/m.giraud/dumux38bis/dumux/dumux-rosi/experimental/fixedPointIter2/scripts/../modules/solverbase.py", line 644, in _map
    assert len(indices) == len(x), "_map: indices and values have different length"
AssertionError: _map: indices and values have different length

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "launchTillage.py", line 8, in <module>
    results_dir = mainTillage.XcGrowth(25.5, 30.,0,spellData )
  File "/mnt/beegfs-ssd/home/m.giraud/dumux38bis/dumux/dumux-rosi/experimental/fixedPointIter2/scripts/mainTillage.py", line 106, in XcGrowth
    s = scenario_setup.create_soil_model(usemoles = usemoles, 
  File "/mnt/beegfs-ssd/home/m.giraud/dumux38bis/dumux/dumux-rosi/experimental/fixedPointIter2/scripts/../inputDataTillage/scenario_setup.py", line 356, in create_soil_model
    s = setupOther(s, p_mean_)
  File "/mnt/beegfs-ssd/home/m.giraud/dumux38bis/dumux/dumux-rosi/experimental/fixedPointIter2/scripts/../inputDataTillage/scenario_setup.py", line 407, in setupOther
    s.initializeProblem(s.maxDt)
  File "/mnt/beegfs-ssd/home/m.giraud/dumux38bis/dumux/dumux-rosi/experimental/fixedPointIter2/scripts/../modules/solverbase.py", line 316, in initializeProblem
    self.cellSurfacesCyl = self._map(self._flat0(comm.gather(self.base.getCellSurfacesCyl(),root=0)), 2) * 1.e4  # m3 -> cm3
  File "/mnt/beegfs-ssd/home/m.giraud/dumux38bis/dumux/dumux-rosi/experimental/fixedPointIter2/scripts/../modules/solverbase.py", line 648, in _map
    raise Exception
Exception
mpirun: Forwarding signal 18 to job
slurmstepd: error: *** JOB 30225 ON node14 CANCELLED AT 2024-08-08T18:51:19 ***
