/mnt/beegfs-ssd/home/m.giraud/DumuxDune27/DUMUX/dumux-rosi/python/paperSc/cyl3plant.py:1427: RuntimeWarning: invalid value encountered in divide
  abs(s.bulkMassCError1dsAll_abs[nc]*100/buTotCAfterEach[nc]),
/home/m.giraud/.local/lib/python3.8/site-packages/numpy/core/fromnumeric.py:3432: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/m.giraud/.local/lib/python3.8/site-packages/numpy/core/_methods.py:190: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/mnt/beegfs-ssd/home/m.giraud/DumuxDune27/DUMUX/dumux-rosi/python/paperSc/cyl3plant.py:1427: RuntimeWarning: invalid value encountered in divide
  abs(s.bulkMassCError1dsAll_abs[nc]*100/buTotCAfterEach[nc]),
/home/m.giraud/.local/lib/python3.8/site-packages/numpy/core/fromnumeric.py:3432: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/m.giraud/.local/lib/python3.8/site-packages/numpy/core/_methods.py:190: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/mnt/beegfs-ssd/home/m.giraud/DumuxDune27/DUMUX/dumux-rosi/python/paperSc/cyl3plant.py:1427: RuntimeWarning: invalid value encountered in divide
  abs(s.bulkMassCError1dsAll_abs[nc]*100/buTotCAfterEach[nc]),
/home/m.giraud/.local/lib/python3.8/site-packages/numpy/core/fromnumeric.py:3432: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/m.giraud/.local/lib/python3.8/site-packages/numpy/core/_methods.py:190: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/mnt/beegfs-ssd/home/m.giraud/DumuxDune27/DUMUX/dumux-rosi/python/paperSc/cyl3plant.py:1427: RuntimeWarning: invalid value encountered in divide
  abs(s.bulkMassCError1dsAll_abs[nc]*100/buTotCAfterEach[nc]),
/home/m.giraud/.local/lib/python3.8/site-packages/numpy/core/fromnumeric.py:3432: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/m.giraud/.local/lib/python3.8/site-packages/numpy/core/_methods.py:190: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/mnt/beegfs-ssd/home/m.giraud/DumuxDune27/DUMUX/dumux-rosi/python/paperSc/cyl3plant.py:1427: RuntimeWarning: invalid value encountered in divide
  abs(s.bulkMassCError1dsAll_abs[nc]*100/buTotCAfterEach[nc]),
/home/m.giraud/.local/lib/python3.8/site-packages/numpy/core/fromnumeric.py:3432: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/m.giraud/.local/lib/python3.8/site-packages/numpy/core/_methods.py:190: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/mnt/beegfs-ssd/home/m.giraud/DumuxDune27/DUMUX/dumux-rosi/python/paperSc/cyl3plant.py:1427: RuntimeWarning: invalid value encountered in divide
  abs(s.bulkMassCError1dsAll_abs[nc]*100/buTotCAfterEach[nc]),
/home/m.giraud/.local/lib/python3.8/site-packages/numpy/core/fromnumeric.py:3432: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/m.giraud/.local/lib/python3.8/site-packages/numpy/core/_methods.py:190: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/mnt/beegfs-ssd/home/m.giraud/DumuxDune27/DUMUX/dumux-rosi/python/paperSc/cyl3plant.py:1427: RuntimeWarning: invalid value encountered in divide
  abs(s.bulkMassCError1dsAll_abs[nc]*100/buTotCAfterEach[nc]),
/home/m.giraud/.local/lib/python3.8/site-packages/numpy/core/fromnumeric.py:3432: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/m.giraud/.local/lib/python3.8/site-packages/numpy/core/_methods.py:190: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/mnt/beegfs-ssd/home/m.giraud/DumuxDune27/DUMUX/dumux-rosi/python/paperSc/cyl3plant.py:1427: RuntimeWarning: invalid value encountered in divide
  abs(s.bulkMassCError1dsAll_abs[nc]*100/buTotCAfterEach[nc]),
/home/m.giraud/.local/lib/python3.8/site-packages/numpy/core/fromnumeric.py:3432: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/m.giraud/.local/lib/python3.8/site-packages/numpy/core/_methods.py:190: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/mnt/beegfs-ssd/home/m.giraud/DumuxDune27/DUMUX/dumux-rosi/python/paperSc/cyl3plant.py:1427: RuntimeWarning: invalid value encountered in divide
  abs(s.bulkMassCError1dsAll_abs[nc]*100/buTotCAfterEach[nc]),
/home/m.giraud/.local/lib/python3.8/site-packages/numpy/core/fromnumeric.py:3432: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/m.giraud/.local/lib/python3.8/site-packages/numpy/core/_methods.py:190: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/mnt/beegfs-ssd/home/m.giraud/DumuxDune27/DUMUX/dumux-rosi/python/paperSc/cyl3plant.py:1427: RuntimeWarning: invalid value encountered in divide
  abs(s.bulkMassCError1dsAll_abs[nc]*100/buTotCAfterEach[nc]),
/home/m.giraud/.local/lib/python3.8/site-packages/numpy/core/fromnumeric.py:3432: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/m.giraud/.local/lib/python3.8/site-packages/numpy/core/_methods.py:190: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/mnt/beegfs-ssd/home/m.giraud/DumuxDune27/DUMUX/dumux-rosi/python/paperSc/cyl3plant.py:1427: RuntimeWarning: invalid value encountered in divide
  abs(s.bulkMassCError1dsAll_abs[nc]*100/buTotCAfterEach[nc]),
/home/m.giraud/.local/lib/python3.8/site-packages/numpy/core/fromnumeric.py:3432: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/m.giraud/.local/lib/python3.8/site-packages/numpy/core/_methods.py:190: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/mnt/beegfs-ssd/home/m.giraud/DumuxDune27/DUMUX/dumux-rosi/python/paperSc/cyl3plant.py:1427: RuntimeWarning: invalid value encountered in divide
  abs(s.bulkMassCError1dsAll_abs[nc]*100/buTotCAfterEach[nc]),
/home/m.giraud/.local/lib/python3.8/site-packages/numpy/core/fromnumeric.py:3432: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/m.giraud/.local/lib/python3.8/site-packages/numpy/core/_methods.py:190: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/mnt/beegfs-ssd/home/m.giraud/DumuxDune27/DUMUX/dumux-rosi/python/paperSc/cyl3plant.py:1427: RuntimeWarning: invalid value encountered in divide
  abs(s.bulkMassCError1dsAll_abs[nc]*100/buTotCAfterEach[nc]),
/home/m.giraud/.local/lib/python3.8/site-packages/numpy/core/fromnumeric.py:3432: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/m.giraud/.local/lib/python3.8/site-packages/numpy/core/_methods.py:190: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/mnt/beegfs-ssd/home/m.giraud/DumuxDune27/DUMUX/dumux-rosi/python/paperSc/cyl3plant.py:1427: RuntimeWarning: invalid value encountered in divide
  abs(s.bulkMassCError1dsAll_abs[nc]*100/buTotCAfterEach[nc]),
/home/m.giraud/.local/lib/python3.8/site-packages/numpy/core/fromnumeric.py:3432: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/m.giraud/.local/lib/python3.8/site-packages/numpy/core/_methods.py:190: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/mnt/beegfs-ssd/home/m.giraud/DumuxDune27/DUMUX/dumux-rosi/python/paperSc/cyl3plant.py:1427: RuntimeWarning: invalid value encountered in divide
  abs(s.bulkMassCError1dsAll_abs[nc]*100/buTotCAfterEach[nc]),
/home/m.giraud/.local/lib/python3.8/site-packages/numpy/core/fromnumeric.py:3432: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/m.giraud/.local/lib/python3.8/site-packages/numpy/core/_methods.py:190: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/mnt/beegfs-ssd/home/m.giraud/DumuxDune27/DUMUX/dumux-rosi/python/paperSc/cyl3plant.py:1427: RuntimeWarning: invalid value encountered in divide
  abs(s.bulkMassCError1dsAll_abs[nc]*100/buTotCAfterEach[nc]),
/home/m.giraud/.local/lib/python3.8/site-packages/numpy/core/fromnumeric.py:3432: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/m.giraud/.local/lib/python3.8/site-packages/numpy/core/_methods.py:190: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/mnt/beegfs-ssd/home/m.giraud/DumuxDune27/DUMUX/dumux-rosi/python/paperSc/cyl3plant.py:1427: RuntimeWarning: invalid value encountered in divide
  abs(s.bulkMassCError1dsAll_abs[nc]*100/buTotCAfterEach[nc]),
/home/m.giraud/.local/lib/python3.8/site-packages/numpy/core/fromnumeric.py:3432: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/m.giraud/.local/lib/python3.8/site-packages/numpy/core/_methods.py:190: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/mnt/beegfs-ssd/home/m.giraud/DumuxDune27/DUMUX/dumux-rosi/python/paperSc/cyl3plant.py:1427: RuntimeWarning: invalid value encountered in divide
  abs(s.bulkMassCError1dsAll_abs[nc]*100/buTotCAfterEach[nc]),
/home/m.giraud/.local/lib/python3.8/site-packages/numpy/core/fromnumeric.py:3432: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/m.giraud/.local/lib/python3.8/site-packages/numpy/core/_methods.py:190: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/mnt/beegfs-ssd/home/m.giraud/DumuxDune27/DUMUX/dumux-rosi/python/paperSc/cyl3plant.py:1427: RuntimeWarning: invalid value encountered in divide
  abs(s.bulkMassCError1dsAll_abs[nc]*100/buTotCAfterEach[nc]),
/home/m.giraud/.local/lib/python3.8/site-packages/numpy/core/fromnumeric.py:3432: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/m.giraud/.local/lib/python3.8/site-packages/numpy/core/_methods.py:190: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/mnt/beegfs-ssd/home/m.giraud/DumuxDune27/DUMUX/dumux-rosi/python/paperSc/cyl3plant.py:1427: RuntimeWarning: invalid value encountered in divide
  abs(s.bulkMassCError1dsAll_abs[nc]*100/buTotCAfterEach[nc]),
/home/m.giraud/.local/lib/python3.8/site-packages/numpy/core/fromnumeric.py:3432: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/m.giraud/.local/lib/python3.8/site-packages/numpy/core/_methods.py:190: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/mnt/beegfs-ssd/home/m.giraud/DumuxDune27/DUMUX/dumux-rosi/python/paperSc/cyl3plant.py:1427: RuntimeWarning: invalid value encountered in divide
  abs(s.bulkMassCError1dsAll_abs[nc]*100/buTotCAfterEach[nc]),
/home/m.giraud/.local/lib/python3.8/site-packages/numpy/core/fromnumeric.py:3432: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/m.giraud/.local/lib/python3.8/site-packages/numpy/core/_methods.py:190: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/mnt/beegfs-ssd/home/m.giraud/DumuxDune27/DUMUX/dumux-rosi/python/paperSc/cyl3plant.py:1427: RuntimeWarning: invalid value encountered in divide
  abs(s.bulkMassCError1dsAll_abs[nc]*100/buTotCAfterEach[nc]),
/home/m.giraud/.local/lib/python3.8/site-packages/numpy/core/fromnumeric.py:3432: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/m.giraud/.local/lib/python3.8/site-packages/numpy/core/_methods.py:190: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/mnt/beegfs-ssd/home/m.giraud/DumuxDune27/DUMUX/dumux-rosi/python/paperSc/cyl3plant.py:1427: RuntimeWarning: invalid value encountered in divide
  abs(s.bulkMassCError1dsAll_abs[nc]*100/buTotCAfterEach[nc]),
/home/m.giraud/.local/lib/python3.8/site-packages/numpy/core/fromnumeric.py:3432: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/m.giraud/.local/lib/python3.8/site-packages/numpy/core/_methods.py:190: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/mnt/beegfs-ssd/home/m.giraud/DumuxDune27/DUMUX/dumux-rosi/python/paperSc/cyl3plant.py:1427: RuntimeWarning: invalid value encountered in divide
  abs(s.bulkMassCError1dsAll_abs[nc]*100/buTotCAfterEach[nc]),
/home/m.giraud/.local/lib/python3.8/site-packages/numpy/core/fromnumeric.py:3432: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/m.giraud/.local/lib/python3.8/site-packages/numpy/core/_methods.py:190: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/mnt/beegfs-ssd/home/m.giraud/DumuxDune27/DUMUX/dumux-rosi/python/paperSc/cyl3plant.py:1427: RuntimeWarning: invalid value encountered in divide
  abs(s.bulkMassCError1dsAll_abs[nc]*100/buTotCAfterEach[nc]),
/home/m.giraud/.local/lib/python3.8/site-packages/numpy/core/fromnumeric.py:3432: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/m.giraud/.local/lib/python3.8/site-packages/numpy/core/_methods.py:190: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/mnt/beegfs-ssd/home/m.giraud/DumuxDune27/DUMUX/dumux-rosi/python/paperSc/cyl3plant.py:1427: RuntimeWarning: invalid value encountered in divide
  abs(s.bulkMassCError1dsAll_abs[nc]*100/buTotCAfterEach[nc]),
/home/m.giraud/.local/lib/python3.8/site-packages/numpy/core/fromnumeric.py:3432: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/m.giraud/.local/lib/python3.8/site-packages/numpy/core/_methods.py:190: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/mnt/beegfs-ssd/home/m.giraud/DumuxDune27/DUMUX/dumux-rosi/python/paperSc/cyl3plant.py:1427: RuntimeWarning: invalid value encountered in divide
  abs(s.bulkMassCError1dsAll_abs[nc]*100/buTotCAfterEach[nc]),
/home/m.giraud/.local/lib/python3.8/site-packages/numpy/core/fromnumeric.py:3432: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/m.giraud/.local/lib/python3.8/site-packages/numpy/core/_methods.py:190: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/mnt/beegfs-ssd/home/m.giraud/DumuxDune27/DUMUX/dumux-rosi/python/paperSc/cyl3plant.py:1427: RuntimeWarning: invalid value encountered in divide
  abs(s.bulkMassCError1dsAll_abs[nc]*100/buTotCAfterEach[nc]),
/home/m.giraud/.local/lib/python3.8/site-packages/numpy/core/fromnumeric.py:3432: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/m.giraud/.local/lib/python3.8/site-packages/numpy/core/_methods.py:190: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/mnt/beegfs-ssd/home/m.giraud/DumuxDune27/DUMUX/dumux-rosi/python/paperSc/cyl3plant.py:1427: RuntimeWarning: invalid value encountered in divide
  abs(s.bulkMassCError1dsAll_abs[nc]*100/buTotCAfterEach[nc]),
Traceback (most recent call last):
  File "XcGrowth.py", line 1002, in <module>
    results_dir = XcGrowth(initsim, mode,simMax,extraName,paramIndx_base,spellData )
  File "XcGrowth.py", line 483, in XcGrowth
    net_sol_flux_, net_flux_, seg_fluxes__, real_dtinner,failedLoop, n_iter_inner_max = cyl3.simulate_const(s, 
  File "/mnt/beegfs-ssd/home/m.giraud/DumuxDune27/DUMUX/dumux-rosi/python/paperSc/cyl3plant.py", line 261, in simulate_const
    r.save()  
  File "/mnt/beegfs-ssd/home/m.giraud/DumuxDune27/DUMUX/dumux-rosi/python/paperSc/../modules_fpit/rhizo_modelsPlant.py", line 141, in save
    cyl.save()
AttributeError: 'AirSegment' object has no attribute 'save'
Traceback (most recent call last):
  File "XcGrowth.py", line 1002, in <module>
    results_dir = XcGrowth(initsim, mode,simMax,extraName,paramIndx_base,spellData )
  File "XcGrowth.py", line 483, in XcGrowth
    net_sol_flux_, net_flux_, seg_fluxes__, real_dtinner,failedLoop, n_iter_inner_max = cyl3.simulate_const(s, 
  File "/mnt/beegfs-ssd/home/m.giraud/DumuxDune27/DUMUX/dumux-rosi/python/paperSc/cyl3plant.py", line 261, in simulate_const
    r.save()  
  File "/mnt/beegfs-ssd/home/m.giraud/DumuxDune27/DUMUX/dumux-rosi/python/paperSc/../modules_fpit/rhizo_modelsPlant.py", line 141, in save
    cyl.save()
AttributeError: 'AirSegment' object has no attribute 'save'
Traceback (most recent call last):
  File "XcGrowth.py", line 1002, in <module>
    results_dir = XcGrowth(initsim, mode,simMax,extraName,paramIndx_base,spellData )
  File "XcGrowth.py", line 483, in XcGrowth
    net_sol_flux_, net_flux_, seg_fluxes__, real_dtinner,failedLoop, n_iter_inner_max = cyl3.simulate_const(s, 
  File "/mnt/beegfs-ssd/home/m.giraud/DumuxDune27/DUMUX/dumux-rosi/python/paperSc/cyl3plant.py", line 261, in simulate_const
    r.save()  
  File "/mnt/beegfs-ssd/home/m.giraud/DumuxDune27/DUMUX/dumux-rosi/python/paperSc/../modules_fpit/rhizo_modelsPlant.py", line 141, in save
    cyl.save()
AttributeError: 'AirSegment' object has no attribute 'save'
Traceback (most recent call last):
  File "XcGrowth.py", line 1002, in <module>
    results_dir = XcGrowth(initsim, mode,simMax,extraName,paramIndx_base,spellData )
  File "XcGrowth.py", line 483, in XcGrowth
    net_sol_flux_, net_flux_, seg_fluxes__, real_dtinner,failedLoop, n_iter_inner_max = cyl3.simulate_const(s, 
  File "/mnt/beegfs-ssd/home/m.giraud/DumuxDune27/DUMUX/dumux-rosi/python/paperSc/cyl3plant.py", line 261, in simulate_const
    r.save()  
  File "/mnt/beegfs-ssd/home/m.giraud/DumuxDune27/DUMUX/dumux-rosi/python/paperSc/../modules_fpit/rhizo_modelsPlant.py", line 141, in save
    cyl.save()
AttributeError: 'AirSegment' object has no attribute 'save'
Traceback (most recent call last):
  File "XcGrowth.py", line 1002, in <module>
    results_dir = XcGrowth(initsim, mode,simMax,extraName,paramIndx_base,spellData )
  File "XcGrowth.py", line 483, in XcGrowth
    net_sol_flux_, net_flux_, seg_fluxes__, real_dtinner,failedLoop, n_iter_inner_max = cyl3.simulate_const(s, 
  File "/mnt/beegfs-ssd/home/m.giraud/DumuxDune27/DUMUX/dumux-rosi/python/paperSc/cyl3plant.py", line 261, in simulate_const
    r.save()  
  File "/mnt/beegfs-ssd/home/m.giraud/DumuxDune27/DUMUX/dumux-rosi/python/paperSc/../modules_fpit/rhizo_modelsPlant.py", line 141, in save
    cyl.save()
AttributeError: 'AirSegment' object has no attribute 'save'
Traceback (most recent call last):
  File "XcGrowth.py", line 1002, in <module>
    results_dir = XcGrowth(initsim, mode,simMax,extraName,paramIndx_base,spellData )
  File "XcGrowth.py", line 483, in XcGrowth
    net_sol_flux_, net_flux_, seg_fluxes__, real_dtinner,failedLoop, n_iter_inner_max = cyl3.simulate_const(s, 
  File "/mnt/beegfs-ssd/home/m.giraud/DumuxDune27/DUMUX/dumux-rosi/python/paperSc/cyl3plant.py", line 261, in simulate_const
    r.save()  
  File "/mnt/beegfs-ssd/home/m.giraud/DumuxDune27/DUMUX/dumux-rosi/python/paperSc/../modules_fpit/rhizo_modelsPlant.py", line 141, in save
    cyl.save()
AttributeError: 'AirSegment' object has no attribute 'save'
Traceback (most recent call last):
  File "XcGrowth.py", line 1002, in <module>
    results_dir = XcGrowth(initsim, mode,simMax,extraName,paramIndx_base,spellData )
  File "XcGrowth.py", line 483, in XcGrowth
    net_sol_flux_, net_flux_, seg_fluxes__, real_dtinner,failedLoop, n_iter_inner_max = cyl3.simulate_const(s, 
  File "/mnt/beegfs-ssd/home/m.giraud/DumuxDune27/DUMUX/dumux-rosi/python/paperSc/cyl3plant.py", line 261, in simulate_const
    r.save()  
  File "/mnt/beegfs-ssd/home/m.giraud/DumuxDune27/DUMUX/dumux-rosi/python/paperSc/../modules_fpit/rhizo_modelsPlant.py", line 141, in save
    cyl.save()
AttributeError: 'AirSegment' object has no attribute 'save'
Traceback (most recent call last):
  File "XcGrowth.py", line 1002, in <module>
    results_dir = XcGrowth(initsim, mode,simMax,extraName,paramIndx_base,spellData )
  File "XcGrowth.py", line 483, in XcGrowth
    net_sol_flux_, net_flux_, seg_fluxes__, real_dtinner,failedLoop, n_iter_inner_max = cyl3.simulate_const(s, 
  File "/mnt/beegfs-ssd/home/m.giraud/DumuxDune27/DUMUX/dumux-rosi/python/paperSc/cyl3plant.py", line 261, in simulate_const
    r.save()  
  File "/mnt/beegfs-ssd/home/m.giraud/DumuxDune27/DUMUX/dumux-rosi/python/paperSc/../modules_fpit/rhizo_modelsPlant.py", line 141, in save
    cyl.save()
AttributeError: 'AirSegment' object has no attribute 'save'
Traceback (most recent call last):
  File "XcGrowth.py", line 1002, in <module>
    results_dir = XcGrowth(initsim, mode,simMax,extraName,paramIndx_base,spellData )
  File "XcGrowth.py", line 483, in XcGrowth
    net_sol_flux_, net_flux_, seg_fluxes__, real_dtinner,failedLoop, n_iter_inner_max = cyl3.simulate_const(s, 
  File "/mnt/beegfs-ssd/home/m.giraud/DumuxDune27/DUMUX/dumux-rosi/python/paperSc/cyl3plant.py", line 261, in simulate_const
    r.save()  
  File "/mnt/beegfs-ssd/home/m.giraud/DumuxDune27/DUMUX/dumux-rosi/python/paperSc/../modules_fpit/rhizo_modelsPlant.py", line 141, in save
    cyl.save()
AttributeError: 'AirSegment' object has no attribute 'save'
Traceback (most recent call last):
  File "XcGrowth.py", line 1002, in <module>
    results_dir = XcGrowth(initsim, mode,simMax,extraName,paramIndx_base,spellData )
  File "XcGrowth.py", line 483, in XcGrowth
    net_sol_flux_, net_flux_, seg_fluxes__, real_dtinner,failedLoop, n_iter_inner_max = cyl3.simulate_const(s, 
  File "/mnt/beegfs-ssd/home/m.giraud/DumuxDune27/DUMUX/dumux-rosi/python/paperSc/cyl3plant.py", line 261, in simulate_const
    r.save()  
  File "/mnt/beegfs-ssd/home/m.giraud/DumuxDune27/DUMUX/dumux-rosi/python/paperSc/../modules_fpit/rhizo_modelsPlant.py", line 141, in save
    cyl.save()
AttributeError: 'AirSegment' object has no attribute 'save'
Traceback (most recent call last):
  File "XcGrowth.py", line 1002, in <module>
    results_dir = XcGrowth(initsim, mode,simMax,extraName,paramIndx_base,spellData )
  File "XcGrowth.py", line 483, in XcGrowth
    net_sol_flux_, net_flux_, seg_fluxes__, real_dtinner,failedLoop, n_iter_inner_max = cyl3.simulate_const(s, 
  File "/mnt/beegfs-ssd/home/m.giraud/DumuxDune27/DUMUX/dumux-rosi/python/paperSc/cyl3plant.py", line 261, in simulate_const
    r.save()  
  File "/mnt/beegfs-ssd/home/m.giraud/DumuxDune27/DUMUX/dumux-rosi/python/paperSc/../modules_fpit/rhizo_modelsPlant.py", line 141, in save
    cyl.save()
AttributeError: 'AirSegment' object has no attribute 'save'
Traceback (most recent call last):
  File "XcGrowth.py", line 1002, in <module>
    results_dir = XcGrowth(initsim, mode,simMax,extraName,paramIndx_base,spellData )
  File "XcGrowth.py", line 483, in XcGrowth
    net_sol_flux_, net_flux_, seg_fluxes__, real_dtinner,failedLoop, n_iter_inner_max = cyl3.simulate_const(s, 
  File "/mnt/beegfs-ssd/home/m.giraud/DumuxDune27/DUMUX/dumux-rosi/python/paperSc/cyl3plant.py", line 261, in simulate_const
    r.save()  
  File "/mnt/beegfs-ssd/home/m.giraud/DumuxDune27/DUMUX/dumux-rosi/python/paperSc/../modules_fpit/rhizo_modelsPlant.py", line 141, in save
    cyl.save()
AttributeError: 'AirSegment' object has no attribute 'save'
Traceback (most recent call last):
  File "XcGrowth.py", line 1002, in <module>
    results_dir = XcGrowth(initsim, mode,simMax,extraName,paramIndx_base,spellData )
  File "XcGrowth.py", line 483, in XcGrowth
    net_sol_flux_, net_flux_, seg_fluxes__, real_dtinner,failedLoop, n_iter_inner_max = cyl3.simulate_const(s, 
  File "/mnt/beegfs-ssd/home/m.giraud/DumuxDune27/DUMUX/dumux-rosi/python/paperSc/cyl3plant.py", line 261, in simulate_const
    r.save()  
  File "/mnt/beegfs-ssd/home/m.giraud/DumuxDune27/DUMUX/dumux-rosi/python/paperSc/../modules_fpit/rhizo_modelsPlant.py", line 141, in save
    cyl.save()
AttributeError: 'AirSegment' object has no attribute 'save'
Traceback (most recent call last):
  File "XcGrowth.py", line 1002, in <module>
    results_dir = XcGrowth(initsim, mode,simMax,extraName,paramIndx_base,spellData )
  File "XcGrowth.py", line 483, in XcGrowth
    net_sol_flux_, net_flux_, seg_fluxes__, real_dtinner,failedLoop, n_iter_inner_max = cyl3.simulate_const(s, 
  File "/mnt/beegfs-ssd/home/m.giraud/DumuxDune27/DUMUX/dumux-rosi/python/paperSc/cyl3plant.py", line 261, in simulate_const
    r.save()  
  File "/mnt/beegfs-ssd/home/m.giraud/DumuxDune27/DUMUX/dumux-rosi/python/paperSc/../modules_fpit/rhizo_modelsPlant.py", line 141, in save
    cyl.save()
AttributeError: 'AirSegment' object has no attribute 'save'
Traceback (most recent call last):
  File "XcGrowth.py", line 1002, in <module>
    results_dir = XcGrowth(initsim, mode,simMax,extraName,paramIndx_base,spellData )
  File "XcGrowth.py", line 483, in XcGrowth
    net_sol_flux_, net_flux_, seg_fluxes__, real_dtinner,failedLoop, n_iter_inner_max = cyl3.simulate_const(s, 
  File "/mnt/beegfs-ssd/home/m.giraud/DumuxDune27/DUMUX/dumux-rosi/python/paperSc/cyl3plant.py", line 261, in simulate_const
    r.save()  
  File "/mnt/beegfs-ssd/home/m.giraud/DumuxDune27/DUMUX/dumux-rosi/python/paperSc/../modules_fpit/rhizo_modelsPlant.py", line 141, in save
    cyl.save()
AttributeError: 'AirSegment' object has no attribute 'save'
Traceback (most recent call last):
  File "XcGrowth.py", line 1002, in <module>
    results_dir = XcGrowth(initsim, mode,simMax,extraName,paramIndx_base,spellData )
  File "XcGrowth.py", line 483, in XcGrowth
    net_sol_flux_, net_flux_, seg_fluxes__, real_dtinner,failedLoop, n_iter_inner_max = cyl3.simulate_const(s, 
  File "/mnt/beegfs-ssd/home/m.giraud/DumuxDune27/DUMUX/dumux-rosi/python/paperSc/cyl3plant.py", line 261, in simulate_const
    r.save()  
  File "/mnt/beegfs-ssd/home/m.giraud/DumuxDune27/DUMUX/dumux-rosi/python/paperSc/../modules_fpit/rhizo_modelsPlant.py", line 141, in save
    cyl.save()
AttributeError: 'AirSegment' object has no attribute 'save'
Traceback (most recent call last):
  File "XcGrowth.py", line 1002, in <module>
    results_dir = XcGrowth(initsim, mode,simMax,extraName,paramIndx_base,spellData )
  File "XcGrowth.py", line 483, in XcGrowth
    net_sol_flux_, net_flux_, seg_fluxes__, real_dtinner,failedLoop, n_iter_inner_max = cyl3.simulate_const(s, 
  File "/mnt/beegfs-ssd/home/m.giraud/DumuxDune27/DUMUX/dumux-rosi/python/paperSc/cyl3plant.py", line 261, in simulate_const
    r.save()  
  File "/mnt/beegfs-ssd/home/m.giraud/DumuxDune27/DUMUX/dumux-rosi/python/paperSc/../modules_fpit/rhizo_modelsPlant.py", line 141, in save
    cyl.save()
AttributeError: 'AirSegment' object has no attribute 'save'
Traceback (most recent call last):
  File "XcGrowth.py", line 1002, in <module>
    results_dir = XcGrowth(initsim, mode,simMax,extraName,paramIndx_base,spellData )
  File "XcGrowth.py", line 483, in XcGrowth
    net_sol_flux_, net_flux_, seg_fluxes__, real_dtinner,failedLoop, n_iter_inner_max = cyl3.simulate_const(s, 
  File "/mnt/beegfs-ssd/home/m.giraud/DumuxDune27/DUMUX/dumux-rosi/python/paperSc/cyl3plant.py", line 261, in simulate_const
    r.save()  
  File "/mnt/beegfs-ssd/home/m.giraud/DumuxDune27/DUMUX/dumux-rosi/python/paperSc/../modules_fpit/rhizo_modelsPlant.py", line 141, in save
    cyl.save()
AttributeError: 'AirSegment' object has no attribute 'save'
Traceback (most recent call last):
  File "XcGrowth.py", line 1002, in <module>
    results_dir = XcGrowth(initsim, mode,simMax,extraName,paramIndx_base,spellData )
  File "XcGrowth.py", line 483, in XcGrowth
    net_sol_flux_, net_flux_, seg_fluxes__, real_dtinner,failedLoop, n_iter_inner_max = cyl3.simulate_const(s, 
  File "/mnt/beegfs-ssd/home/m.giraud/DumuxDune27/DUMUX/dumux-rosi/python/paperSc/cyl3plant.py", line 261, in simulate_const
    r.save()  
  File "/mnt/beegfs-ssd/home/m.giraud/DumuxDune27/DUMUX/dumux-rosi/python/paperSc/../modules_fpit/rhizo_modelsPlant.py", line 141, in save
    cyl.save()
AttributeError: 'AirSegment' object has no attribute 'save'
Traceback (most recent call last):
  File "XcGrowth.py", line 1002, in <module>
    results_dir = XcGrowth(initsim, mode,simMax,extraName,paramIndx_base,spellData )
  File "XcGrowth.py", line 483, in XcGrowth
    net_sol_flux_, net_flux_, seg_fluxes__, real_dtinner,failedLoop, n_iter_inner_max = cyl3.simulate_const(s, 
  File "/mnt/beegfs-ssd/home/m.giraud/DumuxDune27/DUMUX/dumux-rosi/python/paperSc/cyl3plant.py", line 261, in simulate_const
    r.save()  
  File "/mnt/beegfs-ssd/home/m.giraud/DumuxDune27/DUMUX/dumux-rosi/python/paperSc/../modules_fpit/rhizo_modelsPlant.py", line 141, in save
    cyl.save()
AttributeError: 'AirSegment' object has no attribute 'save'
Traceback (most recent call last):
  File "XcGrowth.py", line 1002, in <module>
    results_dir = XcGrowth(initsim, mode,simMax,extraName,paramIndx_base,spellData )
  File "XcGrowth.py", line 483, in XcGrowth
    net_sol_flux_, net_flux_, seg_fluxes__, real_dtinner,failedLoop, n_iter_inner_max = cyl3.simulate_const(s, 
  File "/mnt/beegfs-ssd/home/m.giraud/DumuxDune27/DUMUX/dumux-rosi/python/paperSc/cyl3plant.py", line 261, in simulate_const
    r.save()  
  File "/mnt/beegfs-ssd/home/m.giraud/DumuxDune27/DUMUX/dumux-rosi/python/paperSc/../modules_fpit/rhizo_modelsPlant.py", line 141, in save
    cyl.save()
AttributeError: 'AirSegment' object has no attribute 'save'
Traceback (most recent call last):
  File "XcGrowth.py", line 1002, in <module>
    results_dir = XcGrowth(initsim, mode,simMax,extraName,paramIndx_base,spellData )
  File "XcGrowth.py", line 483, in XcGrowth
    net_sol_flux_, net_flux_, seg_fluxes__, real_dtinner,failedLoop, n_iter_inner_max = cyl3.simulate_const(s, 
  File "/mnt/beegfs-ssd/home/m.giraud/DumuxDune27/DUMUX/dumux-rosi/python/paperSc/cyl3plant.py", line 261, in simulate_const
    r.save()  
  File "/mnt/beegfs-ssd/home/m.giraud/DumuxDune27/DUMUX/dumux-rosi/python/paperSc/../modules_fpit/rhizo_modelsPlant.py", line 141, in save
    cyl.save()
AttributeError: 'AirSegment' object has no attribute 'save'
Traceback (most recent call last):
  File "XcGrowth.py", line 1002, in <module>
    results_dir = XcGrowth(initsim, mode,simMax,extraName,paramIndx_base,spellData )
  File "XcGrowth.py", line 483, in XcGrowth
    net_sol_flux_, net_flux_, seg_fluxes__, real_dtinner,failedLoop, n_iter_inner_max = cyl3.simulate_const(s, 
  File "/mnt/beegfs-ssd/home/m.giraud/DumuxDune27/DUMUX/dumux-rosi/python/paperSc/cyl3plant.py", line 261, in simulate_const
    r.save()  
  File "/mnt/beegfs-ssd/home/m.giraud/DumuxDune27/DUMUX/dumux-rosi/python/paperSc/../modules_fpit/rhizo_modelsPlant.py", line 141, in save
    cyl.save()
AttributeError: 'AirSegment' object has no attribute 'save'
Traceback (most recent call last):
  File "XcGrowth.py", line 1002, in <module>
    results_dir = XcGrowth(initsim, mode,simMax,extraName,paramIndx_base,spellData )
  File "XcGrowth.py", line 483, in XcGrowth
    net_sol_flux_, net_flux_, seg_fluxes__, real_dtinner,failedLoop, n_iter_inner_max = cyl3.simulate_const(s, 
  File "/mnt/beegfs-ssd/home/m.giraud/DumuxDune27/DUMUX/dumux-rosi/python/paperSc/cyl3plant.py", line 261, in simulate_const
    r.save()  
  File "/mnt/beegfs-ssd/home/m.giraud/DumuxDune27/DUMUX/dumux-rosi/python/paperSc/../modules_fpit/rhizo_modelsPlant.py", line 141, in save
    cyl.save()
AttributeError: 'AirSegment' object has no attribute 'save'
Traceback (most recent call last):
  File "XcGrowth.py", line 1002, in <module>
    results_dir = XcGrowth(initsim, mode,simMax,extraName,paramIndx_base,spellData )
  File "XcGrowth.py", line 483, in XcGrowth
    net_sol_flux_, net_flux_, seg_fluxes__, real_dtinner,failedLoop, n_iter_inner_max = cyl3.simulate_const(s, 
  File "/mnt/beegfs-ssd/home/m.giraud/DumuxDune27/DUMUX/dumux-rosi/python/paperSc/cyl3plant.py", line 261, in simulate_const
    r.save()  
  File "/mnt/beegfs-ssd/home/m.giraud/DumuxDune27/DUMUX/dumux-rosi/python/paperSc/../modules_fpit/rhizo_modelsPlant.py", line 141, in save
    cyl.save()
AttributeError: 'AirSegment' object has no attribute 'save'
Traceback (most recent call last):
  File "XcGrowth.py", line 1002, in <module>
    results_dir = XcGrowth(initsim, mode,simMax,extraName,paramIndx_base,spellData )
  File "XcGrowth.py", line 483, in XcGrowth
    net_sol_flux_, net_flux_, seg_fluxes__, real_dtinner,failedLoop, n_iter_inner_max = cyl3.simulate_const(s, 
  File "/mnt/beegfs-ssd/home/m.giraud/DumuxDune27/DUMUX/dumux-rosi/python/paperSc/cyl3plant.py", line 261, in simulate_const
    r.save()  
  File "/mnt/beegfs-ssd/home/m.giraud/DumuxDune27/DUMUX/dumux-rosi/python/paperSc/../modules_fpit/rhizo_modelsPlant.py", line 141, in save
    cyl.save()
AttributeError: 'AirSegment' object has no attribute 'save'
Traceback (most recent call last):
  File "XcGrowth.py", line 1002, in <module>
    results_dir = XcGrowth(initsim, mode,simMax,extraName,paramIndx_base,spellData )
  File "XcGrowth.py", line 483, in XcGrowth
    net_sol_flux_, net_flux_, seg_fluxes__, real_dtinner,failedLoop, n_iter_inner_max = cyl3.simulate_const(s, 
  File "/mnt/beegfs-ssd/home/m.giraud/DumuxDune27/DUMUX/dumux-rosi/python/paperSc/cyl3plant.py", line 261, in simulate_const
    r.save()  
  File "/mnt/beegfs-ssd/home/m.giraud/DumuxDune27/DUMUX/dumux-rosi/python/paperSc/../modules_fpit/rhizo_modelsPlant.py", line 141, in save
    cyl.save()
AttributeError: 'AirSegment' object has no attribute 'save'
Traceback (most recent call last):
  File "XcGrowth.py", line 1002, in <module>
    results_dir = XcGrowth(initsim, mode,simMax,extraName,paramIndx_base,spellData )
  File "XcGrowth.py", line 483, in XcGrowth
    net_sol_flux_, net_flux_, seg_fluxes__, real_dtinner,failedLoop, n_iter_inner_max = cyl3.simulate_const(s, 
  File "/mnt/beegfs-ssd/home/m.giraud/DumuxDune27/DUMUX/dumux-rosi/python/paperSc/cyl3plant.py", line 261, in simulate_const
    r.save()  
  File "/mnt/beegfs-ssd/home/m.giraud/DumuxDune27/DUMUX/dumux-rosi/python/paperSc/../modules_fpit/rhizo_modelsPlant.py", line 141, in save
    cyl.save()
AttributeError: 'AirSegment' object has no attribute 'save'
Traceback (most recent call last):
  File "XcGrowth.py", line 1002, in <module>
    results_dir = XcGrowth(initsim, mode,simMax,extraName,paramIndx_base,spellData )
  File "XcGrowth.py", line 483, in XcGrowth
    net_sol_flux_, net_flux_, seg_fluxes__, real_dtinner,failedLoop, n_iter_inner_max = cyl3.simulate_const(s, 
  File "/mnt/beegfs-ssd/home/m.giraud/DumuxDune27/DUMUX/dumux-rosi/python/paperSc/cyl3plant.py", line 261, in simulate_const
    r.save()  
  File "/mnt/beegfs-ssd/home/m.giraud/DumuxDune27/DUMUX/dumux-rosi/python/paperSc/../modules_fpit/rhizo_modelsPlant.py", line 141, in save
    cyl.save()
AttributeError: 'AirSegment' object has no attribute 'save'
mpirun: Forwarding signal 18 to job
slurmstepd: error: *** JOB 22785 ON node10 CANCELLED AT 2024-04-30T16:56:32 ***
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun noticed that process rank 1 with PID 689361 on node node10 exited on signal 15 (Terminated).
--------------------------------------------------------------------------
